tests: setup integration test system
graphql-nexus/nexus-plugin-prisma pull request #406
Opened 2019-09-12 17:51 UTC by jasonkuhrt

This PR does not attempt to actually write out integration tests. This PR is already large. It aims to setup the system to conduct integration tests.

Contributes toward #400

2019-09-13 13:06 UTC, jasonkuhrt commented
Just a meta failure now. Due to the customer matcher we have registered not being picked up by jest.

2019-09-13 13:11 UTC, jasonkuhrt commented on tests/__setup.ts
> +  toTypeCheck(tsConfigFilePath: string) {
I built similar [for nexus](https://github.com/prisma/nexus/blob/develop/tests/_setup.ts). Inline for now but I could see/I think we should extract this out into a jest-ts-test-utils package.

2019-09-13 20:14 UTC, jasonkuhrt commented
Failure on ci that I cannot reproduce locally, doing the exact same steps, seemingly. Need to investigate more deeply.

2019-09-14 02:44 UTC, jasonkuhrt commented on package.json
> +    "graphql": "^14.5.4",
To make peer dep warning from nexus go away

2019-09-14 02:44 UTC, jasonkuhrt commented on src/builder.ts
Actual bug finds!

2019-09-16 09:02 UTC, Weakky requested changes
The integration setup + test looks all good to me, nice work 🙏

2019-09-16 09:02 UTC, Weakky commented on src/builder.ts
I think the reason why it used to be a string is because of the problem you're mentioning in the comment. Even if nexus includes custom scalars in the `AllOutputTypes` type, the type system won't be able to catch them at "dev time" anyway as there's no nexus generated typegen file yet.
In the end, IMO, what matters here is that the surface/public API remain strongly typed. Internally though, we cannot properly type everything as some parts rely on the generated typegen file which happens at runtime. For these cases, I think it's not too bad to use "general types" (such as `string` in this case) as I don't see any other viable option

2019-09-16 09:02 UTC, Weakky commented on tests/app.test.ts
> +  }
`async` is not useful if you're using promise-style callbacks in the function body

2019-09-16 13:08 UTC, jasonkuhrt commented on tests/app.test.ts
> +  }
It removes a vsc warning. Have a better way to do that?

2019-09-16 13:20 UTC, jasonkuhrt commented on src/builder.ts
> the type system won't be able to catch them at "dev time" anyway as there's no nexus generated typegen file yet.

Do you mean dev time of nexus-prisma?

> In the end, IMO, what matters here is that the surface/public API remain strongly typed.

agree

> Internally though, we cannot properly type everything as some parts rely on the generated typegen file which happens at runtime.

My conclusion was different. We can import types from `nexus` and correctly type our plugin.

2019-09-18 19:07 UTC, jasonkuhrt commented on tests/app.test.ts
> +  }
![image](https://user-images.githubusercontent.com/284476/65177708-3d622c80-da25-11e9-903a-3261d7da8efc.png)

Sigh, https://github.com/Microsoft/vscode/issues/61326

Going to disable my vscode `suggestionActions` ✌️

2019-09-18 19:19 UTC, jasonkuhrt commented on src/builder.ts
@Weakky let's pick up the topic of thread next week.

2019-09-18 19:33 UTC, merged