fix: TypeError: Cannot read property 'some' of undefined
graphql-nexus/nexus-plugin-prisma pull request #876
Opened 2020-10-01 21:20 UTC by Albert-Gao

```bash
TypeError: Cannot read property 'some' of undefined
    at transformArg (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:92:23)
    at Array.map (<anonymous>)
    at transformInputType (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:222:2)
    at /Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:53:46
    at Array.map (<anonymous>)
    at transformSchema (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:53:35)
    at transform (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:28:13)
    at Object.exports.getTransformedDmmf (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:16:37)
    at new SchemaBuilder (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/builder.ts:256:7)
    at Object.build (/Users/AlbertGao/codes/teamingCloud/tcBackend/node_modules/nexus-plugin-prisma/src/builder.ts:175:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
AlbertGao@Albert-LottoNZ-Laptop tcBackend % 
```

2020-10-03 05:33 UTC, lrosa007 commented
This seems to be stopping people from using v0.20.0

2020-10-03 13:58 UTC, rightroad commented
the returned InputType needs to include  isNullable and  isRequired following the SchemaArg interface 

```
interface SchemaArg {
    name: string
    inputType: {
      isRequired: boolean
      isList: boolean
      isNullable: boolean
      type: ArgType
      kind: FieldKind
    }
    isRelationFilter?: boolean
  }
```

Solution:

```
 return {
    name: arg.name,
    inputType: {
// Include this 
      isNullable: arg.isNullable,
      isRequired: arg.isRequired,
      ...inputType,
      type: getReturnTypeName(inputType.type),
    },
    // FIXME Why?
    isRelationFilter: undefined,
  }
```
However I still have an issue with the outputTypes: 

```
Type '{ fields: { args: SchemaArg[]; outputType: { type: any; isList: boolean; kind: FieldKind; }; name: string; isRequired: boolean; isNullable?: boolean; }[]; name: string; fieldMap?: Record<...>; isEmbedded?: boolean; }[]' is not assignable to type 'OutputType[]'.
  Type '{ fields: { args: DmmfTypes.SchemaArg[]; outputType: { type: any; isList: boolean; kind: DMMF.FieldKind; }; name: string; isRequired: boolean; isNullable?: boolean; }[]; name: string; fieldMap?: Record<...>; isEmbedded?: boolean; }' is not assignable to type 'OutputType'.
    Types of property 'fields' are incompatible.
      Type '{ args: SchemaArg[]; outputType: { type: any; isList: boolean; kind: FieldKind; }; name: string; isRequired: boolean; isNullable?: boolean; }[]' is not assignable to type 'SchemaField[]'.
        Type '{ args: DmmfTypes.SchemaArg[]; outputType: { type: any; isList: boolean; kind: DMMF.FieldKind; }; name: string; isRequired: boolean; isNullable?: boolean; }' is not assignable to type 'SchemaField'.
          Types of property 'outputType' are incompatible.
            Property 'isRequired' is missing in type '{ type: any; isList: boolean; kind: DMMF.FieldKind; }' but required in type '{ type: string; isList: boolean; isRequired: boolean; kind: FieldKind; }'.ts(2322)
DmmfTypes.ts(76, 7): 'isRequired' is declared here.
DmmfTypes.ts(46, 5): The expected type comes from property 'outputTypes' which is declared here on type 'Schema'
```

2020-10-04 21:17 UTC, Albert-Gao commented
@rightroad Thanks, added :)

2020-10-06 06:58 UTC, Slmii commented
Tried the solution posted by @rightroad but doesnt work for me, i still get `TypeError: Cannot read property 'some' of undefined`...

2020-10-06 09:48 UTC, Albert-Gao commented
@Slmii The current workaround is to patch this file by yourself `node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js`

change the source file won't work, since it is not being used

@jasonkuhrt anyway we can get this merged?

2020-10-06 10:27 UTC, Slmii commented
> @Slmii The current workaround is to patch this file by yourself `node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js`
> 
> change the source file won't work, since it is not being used
> 
> @jasonkuhrt anyway we can get this merged?

I downgraded to prisma 2.7 and everything works fine now.

2020-10-06 11:06 UTC, ricardoalmeida commented
Yes, it also worked for me removing both @prisma/cli and @prisma/client and installing them with the version 2.7.1.

2020-10-06 13:45 UTC, rightroad commented
@Slmii Yeah it's still not working, I had to downgrad to 2.7 again

2020-10-06 15:44 UTC, jasonkuhrt requested changes
Can you clarify the issue here. This makes nexus prisma plugin work with Prisma 2.8?

Please fix the tests and then we'll get this merged assuming no other issues/questions come up.

CC @Weakky

2020-10-06 16:21 UTC, lrosa007 commented
@jasonkuhrt not specifically about the prisma version I don't think.

When setting up nexus and nexus-prisma-plugin with the latest versions of both. The original error from the PR comment shows up.

`TypeError: Cannot read property 'some' of undefined`

`nexus-plugin-prisma/src/dmmf/transformer.ts:92:23`

Literally a bug in the transformer

there is a typo in there. `args.inputType` should be `args.inputTypes` it seems.

Now whether or not this is because of which prisma version one is using I cannot confirm. I have latest everything and patching this library with this PR fix removes the error that I just quoted.

2020-10-06 17:38 UTC, jasonkuhrt commented
@lrosa007 Sounds good. I will trust the tests once updated.

2020-10-07 02:54 UTC, Albert-Gao commented
OK, so after gave it try, it seems that I underestimate this, 

the core of the issue here is the Prisma Client 2.8.0 update breaks this 0.20.0

And this is just one fix among the all

there are more than the eyes can see

I updated prisma deps to 2.8 and building works, but there are 19 tests failing, and most of them are irrelevant to this change.

We need a systematic update to Prisma 2.8 to resolve this issue, leave it to the team

2020-10-07 02:54 UTC, closed without merging